image: bradrydzewski/go:1.3

env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin

script:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint

  - go get -t ./...

  - FAIL=$(find ./ -iname "*.go" -exec gofmt -s -l {} \;) && echo "$FAIL" && test -z "$FAIL"
  - go vet ./...
  - FAIL=$(golint ./...) && echo "$FAIL" && test -z "$FAIL"
  - go test -v ./...
  - goveralls -v -service drone.io -repotoken {{COVERALLS_TOKEN}}
  # - go build --tags SOMETAG

notify:
    email:
        recipients:
            - distribution@docker.com

    slack:
        team: docker
        channel: "#distribution"
        username: mom
        token: {{SLACK_TOKEN}}
        on_success: true
        on_failure: true
