image: dmp42/go:stable

script:
  - go get -t ./...

  - FAIL=$(find ./ -iname "*.go" -exec gofmt -s -l {} \;) && echo "$FAIL" && test -z "$FAIL"
  - go vet ./...
  - FAIL=$(golint ./...) && echo "$FAIL" && test -z "$FAIL"
  - go test -v ./...
  - goveralls -v -service drone.io -repotoken {{COVERALLS_TOKEN}}
  # - go build --tags SOMETAG

notify:
    email:
        recipients:
            - distribution@docker.com

    slack:
        team: docker
        channel: "#dt"
        username: mom
        token: {{SLACK_TOKEN}}
        on_success: true
        on_failure: true
