# UI Development compose file
#
# Usage:
#
# 1) Run the bootstrapper
#   $ docker run --rm -i -v /var/run/docker.sock:/var/run/docker.sock --name ucp docker/ucp install
#
# 2) Create our .env envfile
#   Linux:
#   $ echo "CONTROLLER_URL=https://$(ip -4 -o addr show dev docker0 | cut -f7 -d' '| cut -f1 -d/):443" > .env
#   Mac:
#   $ echo "CONTROLLER_URL=https://$(docker-machine ip default):443\nPOLL=true" > .env
#
# 3) Run compose
#   $ docker-compose -f docker-compose.ui.yml up
#
# 4) Open UCP in browser (Mac Only)
#   $ open $(echo "http://"$(docker-machine ip default)":9090")

webpack-dev-server:
    image: "node:6.2"
    command: bash -c "cd controller/static && ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.config.dev.js --progress --host 0.0.0.0 --port 9090 --inline"
    working_dir: /go/src/github.com/docker/orca
    volumes:
        - ".:/go/src/github.com/docker/orca"
    ports:
        - "9090:9090"
    env_file: .env

semantic:
    image: "node:6.2"
    command: bash -c "npm install -g gulp && npm install && npm link gulp && gulp build && gulp watch"
    working_dir: /workspace
    volumes:
        - "./controller/static/semantic:/workspace"
