dropper:
    ucpurl: 172.17.0.1:444
    ucpinsecuretls: true
    username: admin
    password: password
    hubusername: XXX
    hubpassword: XXX
    moshpitimage: dockerhubenterprise/dtr-moshpit:latest
    servernode: compooter
    serverhost: 172.17.0.1
    numclients: 1
    spread: true
    nocleanup: true
    debug: true
server:
    listenip: 0.0.0.0
    listenport: 1337
    setup:
        dtrurl: 172.17.0.1
        dtrinsecuretls: true
        username: admin
        password: password
        reponame: repo
        numusers: 1000
        numreposperuser: 100
    client:
        dtrurl: 172.17.0.1
        dtrinsecuretls: true
        username: admin
        password: password
        #refreshtoken: 2ce1eeee-c815-44e2-a62e-607748d452cd
        push:
            method: dind-daemon
            namespace: admin
            reponame: repo
            tagname: moshpit
            tagpattern: random
            pushesperbatch: 1
            batches: 10
            pushconcurrency: 1
            layerminbytes: 10000
            layermaxbytes: 10000
            layersizescalepattern: random
            imageminlayers: 10
            imagemaxlayers: 10
            layersscalepattern: random
            retries: 1
        #pull:
        #    method: registry
        #    namespace: admin
        #    reponame: repo
        #    tagname: moshpit
        #    tagpattern: random
        #    pullsesperbatch: 1
        #    batches: 1
        #    pullconcurrency: 1
