dropper:
    ucpurl: 172.17.0.1:444
    ucpinsecuretls: true
    username: admin
    password: password
    moshpitimage: moshpit:latest
    servernode: compooter
    serverhost: 172.17.0.1
    numclients: 1
server:
    listenip: 0.0.0.0
    listenport: 1337
    setup:
        key: value
    client:
        key: value
